---
title: "pixel_tree_length"
author: "Willem Weertman"
date: "4/12/2020"
output: html_document
---

```{r}

setwd("~/R/moving_treeline/CODE")

path_dat <- '../DATA/tree_pixel_data.txt'
dat <- read.csv(path_dat)

```



```{r}

plot(mean_image_pixel_values ~ tree_length,
     data = dat,
     col = rgb(1,0,0,0.4),
     pch = 16,
     ylim = c(25,200))

mean_image = mean(dat$mean_image_pixel_values)
sd_image = sd(dat$mean_image_pixel_values)

points(mean_tree_pixel_values ~ tree_length,
     data = dat,
     col = rgb(0,0,1,0.4),
     pch = 16)

legend('topright',
       legend = c('mean image pixel values',
                  'mean tree pixel values'),
       pch = 16,
       col = c(2, 4),
       bty = 'n')

```


```{r}

plot(mean_image_pixel_values - mean_tree_pixel_values ~ tree_length,
     data = dat,
     col = rgb(0,0,1,0.4),
     pch = 16)

delta_tree_pixel <- dat$mean_image_pixel_values - dat$mean_tree_pixel_values
mean_delta <- round(mean(delta_tree_pixel),3)
sd_delta <- round(sd(delta_tree_pixel),3)

text_mean = paste('mean image-trees = ', mean_delta)
text_sd = paste('sd image-trees = ', sd_delta)

min_delta = min(delta_tree_pixel)
max_delta = max(delta_tree_pixel)

text_max = paste(min_delta, ' < image-tree < ', max_delta)

min_image = min(dat$mean_image_pixel_values)
max_image = max(dat$mean_image_pixel_values)

text_image_max = paste(min_image, ' < image < ', max_image)

min_tree = min(dat$mean_tree_pixel_values)
max_tree = max(dat$mean_tree_pixel_values)

text_tree_max = paste(min_tree, ' < tree < ', max_tree)

legend('topright',
       legend = c(text_mean,
                  text_sd,
                  text_image_max,
                  text_tree_max,
                  text_max),
       bty = 'n',
       lty = c(1,2,NA,NA,NA))

abline(h = mean_delta)
abline(h = mean_delta + sd_delta, lty = 2)
abline(h = mean_delta - sd_delta, lty = 2)

```



Trial 1, model 3

-1.3 < slope < -0.8
45 < mean tree pixels < 112
step = 5

open the data

```{r}

path_filter <- '../DATA/test_dlc_model3_trial_1/results_image_filter.txt'
dat <- read.csv(path_filter)

dat$t_p <- dat$t_dlc_pred/dat$t
dat$t_s <- dat$t_slope/dat$t
dat$t_a_e <- dat$t_array_error/dat$t
dat$t_px <- dat$t_pixel/dat$t
dat$total_filter <- (dat$t_dlc_pred + dat$t_slope + dat$t_array_error + dat$t_pixel)/dat$t

```

lets visualize it now that the numbers are normalized

```{r}

boxplot(dat$t_p, 
        dat$t_s, 
        dat$t_a_e, 
        dat$t_px,
        dat$total_filter,
        names = c('DLC prob filter',
                  'Slope filter',
                  'Array err filter',
                  'M. pixel filter',
                  'Total filter'),
        las = 1)

```
















