---
title: "Moving Treeline - Labeled Data - Linear Model"
author: "Willem Weertman"
date: "4/3/2020"
output: html_document
---

```{r}

setwd("~/R/moving_treeline/CODE")

path_dat <- '../DATA/firstwood/model_3//CollectedData_Willem.csv'
dat <- read.csv(path_dat)


```


```{r}

plot((1:50) , (1:50), 
     type = 'n',
     ylab = 'y coordinates',
     xlab = 'x coordinates')

for (i in 1:nrow(dat)){
  
  x_1 <- dat[i,2]; y_1 <- dat[i,3]#bot
  x_2 <- dat[i,4]; y_2 <- dat[i,5]#top
  
  dat_lm <- data.frame(x=numeric(2),y=numeric(2))
  dat_lm$x <- c(x_1,x_2)
  dat_lm$y <- c(y_1,y_2)

  mod_lm <- lm(y ~ x, data = dat_lm)
  
  intercept_lm <- coef(mod_lm)[[1]]
  slope_lm <- coef(mod_lm)[[2]]
  r_squared_lm <- summary(mod_lm)$r.squared
  
  dat$intercept[i] <- intercept_lm
  dat$slope[i] <- slope_lm
  dat$r_squared[i] <- r_squared_lm
  
  curve(slope_lm*x + intercept_lm, 
        add = T,
        col = rgb(0,0,1,0.1))
  
}

```

```{r}

plot((1:50) , (1:50), 
     type = 'n',
     xlab = 'x coordinates',
     ylab = 'y coordinates')

for (i in 1:nrow(dat)){
  
  x_1 <- dat[i,2]; y_1 <- dat[i,3]#lower, highest y value, lowest x value
  x_2 <- dat[i,4]; y_2 <- dat[i,5]#mid
  x_3 <- dat[i,6]; y_3 <- dat[i,7]#upper, lowest y value, highest y value
  
  dat_lm <- data.frame(x=numeric(3),y=numeric(3))
  dat_lm$x <- c(x_1,x_2,x_3)
  dat_lm$y <- c(y_1,y_2,y_3)
  
  points(y ~ x, 
         data = dat_lm,
         col = rgb(0,0,1,0.1),
         pch = 16)
  
}

```

```{r}


boxplot(dat$intercept/50, abs(dat$slope),
        names = c('Intercept/50', 'abs(Slope)'))

mean_slope <- mean(dat$slope); sd_slope <- sd(dat$slope)
mean_intercept <- mean(dat$intercept); sd_intercept <- sd(dat$intercept)

slope_text <- paste('Slope = ', round(mean_slope,3), ' ± ', round(sd_slope,3))
intercept_text <- paste('Intercept = ', round(mean_intercept,3), ' ± ', round(sd_intercept,3))

legend('bottomright',
       bty = 'n',
       legend = c(slope_text,
                  intercept_text))

```


```{r}

plot((1:50) , (1:50), 
     type = 'n',
     ylab = 'y coordinates',
     xlab = 'x coordinates')

for (i in 1:nrow(dat)){
  
  x_1 <- dat[i,2]; y_1 <- dat[i,3]#bot
  x_2 <- dat[i,4]; y_2 <- dat[i,5]#top
  
  dat_lm <- data.frame(x=numeric(2),y=numeric(2))
  dat_lm$x <- c(x_1,x_2)
  dat_lm$y <- c(y_1,y_2)

  mod_lm <- lm(y ~ x, data = dat_lm)
  
  intercept_lm <- coef(mod_lm)[[1]]
  slope_lm <- coef(mod_lm)[[2]]
  r_squared_lm <- summary(mod_lm)$r.squared
  
  dat$intercept[i] <- intercept_lm
  dat$slope[i] <- slope_lm
  dat$r_squared[i] <- r_squared_lm
  
  curve(slope_lm*x + intercept_lm, 
        add = T,
        col = rgb(0,0,1,0.1))
  
}

mean_slope <- mean(dat$slope); sd_slope <- sd(dat$slope)

min_slope <- round(min(dat$slope),3); max_slope <- round(max(dat$slope),3)

slope_text <- paste('Slopes = ', round(mean_slope,3), ' ± ', round(sd_slope,3))
slope_text_min_max <- paste(min_slope, ' < slope < ' , max_slope)

legend('topright',
       bty = 'n',
       legend = c(slope_text,
                  slope_text_min_max))

```